### ISSUE TITLE
Multiple urls

### ISSUE THREAD

**Issue by co0p** [co0p/x-scrap#3]
In order allow easy scrapping of multiple urls extend the app with multi url Support. 

Possible solution
- change the input flag url to a comma separated list
- iterate over the urls instead of on one shot
- change the printing and output

Optional: make the scrapping concurrent by fanning oit

**Comment by SpasZahariev** [comment]
Hello @co0p, I'm learning go right now and I had some fun implementing this. I tried to write the fannout logic and it kind of works but it changed your original code too much. I'll make a merge request without it
